config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'

  resources :cocktails do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: :destroy
end
# cocktails index show (ingredients and doses) new

# doses new create destroy(ingredient and description to an existing cocktail)

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id, message: 'ingredient already used'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktail, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: :show

  def index
    @cocktails = Cocktail.all
  end

  def show; end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  private

  def find_cocktail
    @cocktail = Cocktail.all.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_dose, only: :destroy
  before_action :find_cocktail, only: [:new, :create]
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose.destroy
    redirect_to @dose.cocktail
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end

  def find_dose
    @dose = Dose.find(params[:id])
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <% if @cocktail.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @cocktail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- [...] all the fields -->
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.submit "Add the cocktail", class: "btn btn-primary" %>
  <% end %>

<% end %>

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>

<% @cocktails.each do |cocktail| %>
  <h3><%= link_to cocktail.name.capitalize, cocktail_path(cocktail) %></h3>
<% end %>

<p><%= link_to "Add a new cocktail", new_cocktail_path %></p>

app/views/cocktails/new.html.erb
<%= render "form" %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name.capitalize %></h1>
<% @cocktail.doses.each do |dose| %>
  <p><%= dose.description %> of <%= dose.ingredient.name.downcase %>
    <%= link_to "Delete", dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>
<p><%= link_to "Add a dose", new_cocktail_dose_path(@cocktail) %></p>
<p><%= link_to "Return to index", cocktails_path %></p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <% if @dose.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @dose.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <h1><%= @cocktail.name %></h1>
    <%= f.input :description %>
    <%= f.association :ingredient %>


    <%= f.submit 'Add a dose', class: "btn btn-primary"%>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>